version: '3'
method: timestamp
run: once

tasks:
  default:
    deps: [test]

  gen:
    desc: |
      Run any generate actions. Useful to run to make an IDE happy.
    deps:
      - task: gen-proto
      - task: gen-mocks

  test:
    deps: [gen-mocks]
    desc: |
      Test all targets.
    vars:
      FLAGS: '{{default "-cover -timeout 30s" .FLAGS}}'
    cmds:
      - exhaustive -default-signifies-exhaustive ./...
      - go test {{.FLAGS}} ./...

  build:
    deps: [gen]
    desc: Build
    cmds:
      - go build ./...

  clean:
    desc: |
      Remove any build artefacts.
    cmds:
      - rm -fr gen/*

  gen-proto:
      cmds:
        - >-
          docker run --rm
          --volume "{{.ROOT_DIR}}:/workspace"
          --workdir /workspace
          {{if eq OS "linux"}}
          --user $(id -u):$(id -g)
          --env XDG_CACHE_HOME=/workspace
          {{end}}
          bufbuild/buf generate .
        - touch gen/proto.touch
      generates:
      - gen/proto.touch

  gen-mocks:
    deps: [gen-proto]
    cmds:
      - mockery --name "RpcReadWriter" --dir types --output ./gen/mocks
      - mockery --dir ./gen/testproto --output ./gen/testproto/mocks --all --keeptree
    sources:
      - "pkg/**/*.go"
      - "goat.go"
    generates:
      - gen/mocks/**/*.go

