version: '3'
method: timestamp
run: once

vars:
  MOCKERY: github.com/vektra/mockery/v2@v2.45.0
  EXHAUSTIVE: github.com/nishanths/exhaustive/cmd/exhaustive@v0.12.0

tasks:
  default:
    deps: [test]

  gen:
    desc: |
      Run any generate actions. Useful to run to make an IDE happy.
    deps:
      - task: gen-proto
      - task: gen-mocks

  test:
    deps:
      - gen-mocks
      - install-deps
    desc: |
      Test all targets.
    vars:
      FLAGS: '{{default "-cover -timeout 30s" .FLAGS}}'
    cmds:
      - go run {{.EXHAUSTIVE}} -default-signifies-exhaustive ./...
      - go test {{.FLAGS}} ./...

  build:
    deps: [gen]
    desc: Build
    cmds:
      - go build ./...

  clean:
    desc: |
      Remove any build artefacts.
    cmds:
      - rm -fr gen/*

  gen-proto:
    method: checksum
    deps:
      - install-deps
    cmds:
      - env "PATH=.bin:$PATH" buf generate
    sources:
      - "goatorepo/*.proto"
      - "testrepo/*.proto"
      - buf.gen.yaml
      - buf.yaml
      - buf.lock
      - Taskfile.yml

  gen-mocks:
    deps: [gen-proto]
    cmds:
      - .bin/mockery --log-level=warn
      - touch gen/mockery.stamp
    sources:
      - "internal/*/*.go"
      - "goat.go"
      - ".mockery.yml"
    generates:
      - gen/mocks/**/*.go

  install-deps:
    cmds:
      - bash scripts/bootstrap
