version: '3'
method: timestamp
run: once

vars:
  MOCKERY: github.com/vektra/mockery/v2@v2.34.2

tasks:
  default:
    deps: [test]

  gen:
    desc: |
      Run any generate actions. Useful to run to make an IDE happy.
    deps:
      - task: gen-proto
      - task: gen-mocks

  test:
    deps: [gen-mocks]
    desc: |
      Test all targets.
    vars:
      FLAGS: '{{default "-cover -timeout 30s" .FLAGS}}'
    cmds:
      - exhaustive -default-signifies-exhaustive ./...
      - go test {{.FLAGS}} ./...

  build:
    deps: [gen]
    desc: Build
    cmds:
      - go build ./...

  clean:
    desc: |
      Remove any build artefacts.
    cmds:
      - rm -fr gen/*

  gen-proto:
    env:
      DISABLE_REQUIRE_UNIMPLEMENTED_SERVERS: 1
    cmds:
      - bash protobuild.sh
      - touch gen/proto.touch
    generates:
      - gen/proto.touch
    sources:
      - protobuild.sh
      - "goatorepo/*.proto"

  gen-mocks:
    deps: [gen-proto]
    cmds:
      - go run {{.MOCKERY}} --log-level=warn
      - touch gen/mockery.stamp
    sources:
      - "internal/*/*.go"
      - "goat.go"
      - ".mockery.yml"
    generates:
      - gen/mockery.stamp

