name: Main

on: push

env:
  CI: true
  # Pinning task version means the setup-task action doesn't need to do a
  # GH API request on every invocation to check the versions available.
  # See: https://github.com/arduino/setup-task
  TASK_VERSION: 3.18.0

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: "true"

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: 1.19

    - run: go version

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Setup project
      run: scripts/bootstrap

    - name: Test
      run: task test
